export {default as SignUp} from './Signup/SignUp'
export {default as Login} from './Login/Login'
export {default as ForgotPass} from './ForgotPassword/ForgotPass'
export {default as Welcome} from './Welcome/Welcome'
export {default as SplashScreen} from './SplashScreen/SplashScreen'